title: Site
sections:
  Users:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: huge
    reports:
      - label: Total Users
        value: "{{ site.totalUsers }}"
      - label: Free Users
        value: "{{ site.freeUsers }}"
      - label: Paid Users
        value: "{{ site.paidUsers }}"
        info: "{{ site.paidUsersPercentage }}"
  Bookmarks:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: medium
    reports:
      - label: Total Bookmarks
        value: "{{ site.totalBookmarks }}"
      - label: Total Tags
        value: "{{ site.totalTags }}"
  Brands:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: medium
    reports:
      - label: Available Brands
        value: "{{ site.totalAvailableBrands }}"
      - label: Brand Coverage
        value: "{{ site.brandCoveragePercentage }}"
      - label: Bookmarks Without Brands
        value: "{{ site.bookmarksWithoutBrands }}"
  MissingBrands:
    type: fields
    fields:
      missingbrands:
        label: Missing Brand Logos
        type: structure
        columns:
          title:
            width: 1/3
          count:
            width: 1/3
          suggested:
            width: 1/3
        fields:
          title:
            label: Bookmark Title
            type: text
          count:
            label: Usage Count
            type: number
          suggested:
            label: Suggested Brand Name
            type: text
        disabled: true
        default: "{{ site.missingBrandsForPanel }}"

