title: Site
sections:
  Users:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: huge
    reports:
      - label: Total Users
        value: "{{ site.totalUsers }}"
      - label: Free Users
        value: "{{ site.freeUsers }}"
      - label: Paid Users
        value: "{{ site.paidUsers }}"
        info: "{{ site.paidUsersPercentage }}"
  Bookmarks:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: medium
    reports:
      - label: Total Bookmarks
        value: "{{ site.totalBookmarks }}"
      - label: Total Tags
        value: "{{ site.totalTags }}"
  Brands:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: medium
    reports:
      - label: Available Brands
        value: "{{ site.totalAvailableBrands }}"
      - label: Brand Coverage
        value: "{{ site.brandCoveragePercentage }}"
      - label: Bookmarks Without Brands
        value: "{{ site.bookmarksWithoutBrands }}"
  MissingBrands:
    headline: Missing Brand Logos
    type: info
    text: "{{ site.missingBrandsText }}"

