title: Site
buttons:
  - open
  - preview
  - inactive-accounts
sections:
  Users:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: huge
    reports:
      - label: Total Users
        value: "{{ site.totalUsers }}"
        icon: users
      - label: Free Users
        value: "{{ site.freeUsers }}"
        info: "{{ site.freeUsersPercentage }}"
        icon: user
      - label: Paid Users
        value: "{{ site.paidUsers }}"
        info: "{{ site.paidUsersPercentage }}"
        icon: money
        theme: positive
      - label: Inactive Users
        value: "{{ site.inactiveUsers }}"
        info: "{{ site.inactiveUsersInfo }}"
        icon: clock
        theme: "{{ site.inactiveUsersTheme }}"
        # same dialog as the "Inactive accounts" button
        dialog: inactive-accounts
  Bookmarks:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: large
    reports:
      - label: Total Bookmarks
        value: "{{ site.totalBookmarks }}"
        info: "{{ site.bookmarksPerUser }}"
        icon: bookmark
      - label: Users With Bookmarks
        value: "{{ site.usersWithBookmarks }}"
        info: "{{ site.usersWithBookmarksInfo }}"
        icon: account
      - label: Total Tags
        value: "{{ site.totalTags }}"
        info: "{{ site.taggedBookmarksInfo }}"
        icon: tag
  Brands:
    type: stats
    # Available size options: small, medium, large, huge. Default is large
    size: large
    reports:
      - label: Brand Coverage
        value: "{{ site.brandCoveragePercentage }}"
        info: "{{ site.brandCoverageInfo }}"
        icon: chart
        theme: "{{ site.brandCoverageTheme }}"
      - label: Bookmarks Without Brands
        value: "{{ site.bookmarksWithoutBrands }}"
        info: Listed below
        icon: alert
        theme: "{{ site.bookmarksWithoutBrandsTheme }}"
      - label: Available Brands
        value: "{{ site.totalAvailableBrands }}"
        info: "{{ site.brandsInUseInfo }}"
        icon: image
  MissingBrands:
    headline: Missing Brand Logos
    type: stats
    size: small
    reports: site.missingBrandsReports
  PartialBrandMatches:
    headline: Partial Brand Matches
    type: stats
    size: small
    reports: site.partialBrandMatchesReports
